backend/src/main/java/com/example/backend/base/controller/BaseController.java, backend/src/main/java/com/example/backend/base/dto/request/BoardRequestDto.java, backend/src/main/java/com/example/backend/base/dto/response/BoardResponseDto.java, backend/src/main/java/com/example/backend/base/entity/BoardEntity.java
[ back / fix ] #7 main 코드 dev에 추가
=> [ back / fix ] #7 main 코드 dev에 추가

backend/src/main/java/com/example/backend/category/entity/Category.java, backend/src/main/java/com/example/backend/exception/ExceptionCode.java, backend/src/main/java/com/example/backend/security/jwt/service/TokenService.java, backend/src/main/java/com/example/backend/security/jwt/util/JwtTokenizer.java, backend/src/main/java/com/example/backend/user/controller/UserController.java
[ back / feat ] : #token에서 역할 가져올 수 있는 기능 구현 완료 (테스트 완료 )
=> [ back / feat ] : #token에서 역할 가져올 수 있는 기능 구현 완료 (테스트 완료 )

backend/src/main/java/com/example/backend/exception/ExceptionCode.java, backend/src/main/java/com/example/backend/security/config/SecurityConfigJuseyo.java, backend/src/main/java/com/example/backend/security/jwt/filter/JwtAuthenticationFilter.java, backend/src/main/java/com/example/backend/user/service/UserService.java
=> [ back / feat ] 22 : 권한 추가

backend/src/main/java/com/example/backend/security/config/SecurityConfigJuseyo.java, backend/src/main/java/com/example/backend/user/controller/UserController.java, backend/src/main/java/com/example/backend/user/service/UserService.java
[ back / fix ] 29 : 로그인 회원가입 권한, 오류 수정
=> [ back / fix ] 29 : 로그인 회원가입 권한, 오류 수정

backend/src/main/java/com/example/backend/category/entity/Category.java, backend/src/main/java/com/example/backend/exception/ExceptionCode.java, backend/src/main/java/com/example/backend/exception/GlobalExceptionHandler.java, backend/src/main/java/com/example/backend/mainDashboard/controller/MainDashBoardController.java, backend/src/main/java/com/example/backend/mainDashboard/dto/MainDashBoardRequestDto.java, backend/src/main/java/com/example/backend/mainDashboard/dto/MainDashBoardResponseDto.java, backend/src/main/java/com/example/backend/mainDashboard/repository/MainDashBoardRepository.java, backend/src/main/java/com/example/backend/mainDashboard/service/MainDashBoardService.java
📒 개요
메인 페이지 CRU
📍 Issue 번호
#19 
🛠️ 작업사항
- 관리자 페이지 등록
- 읽기,수정
- 예외 핸들러 클래스 생성
=> [Back/feat] 19 : 메인 페이지 CRU

backend/src/main/java/com/example/backend/department/controller/DepartmentController.java, backend/src/main/java/com/example/backend/department/dto/DepartmentCreateRequestDTO.java, backend/src/main/java/com/example/backend/department/service/DepartmentService.java, backend/src/main/java/com/example/backend/security/config/SecurityConfigJuseyo.java
부서 CRUD 리팩토링
<br>
부서 requestMapping 경로 변경
부서 생성 및 삭제 권한 로직 변경(컨트롤러단 -> 시큐리티 컨피그의 hasRole)
부서 생성 시 생성자의 관리ID로 부서에 자동 할당
=> [back / refact] 42: 부서 CRUD 리팩토링

backend/src/main/java/com/example/backend/exception/ExceptionCode.java, backend/src/main/java/com/example/backend/exception/GlobalExceptionHandler.java, backend/src/main/java/com/example/backend/user/controller/UserController.java, backend/src/main/java/com/example/backend/user/service/UserService.java
최초 매니저가 일반 매니저의 요청을 승인, 거부, 조회 하는 프로세스 구현
<br>
#40 
<br>
최초 매니저가 관리페이지에 매니저 권한을 요청한 사용자의 요청을 거부할 수 있다. 
최초 매니저가 관리페이지에 매니저 권한을 요청한 사용자의 요청을 승인할 수 있다. 
최초 매니저는 요청, 승인, 거부된 매니저 리스트를 조회할 수 있다. 
일반 매니저는 같은 매니저 요청을 조회, 승인, 거부할 수 없다. 
<br>
=> [ back / feat ] 40  : 최초 매니저가 일반 매니저의 요청을 승인 거부 조회 하는 프로세스 구현

backend/src/main/java/com/example/backend/exception/ExceptionCode.java, backend/src/main/java/com/example/backend/managementDashboard/service/ManagementDashboardService.java, backend/src/main/java/com/example/backend/user/controller/UserController.java, backend/src/main/java/com/example/backend/user/service/UserService.java
관리페이지 생성시 최초 매니저에게 권한 부여
<br>
#46 
<br>
<br>
=> [ back / feat ] 46 : 관리페이지 생성시 최초 매니저에게 권한 부여

backend/src/main/java/com/example/backend/security/config/SecurityConfigJuseyo.java, backend/src/main/java/com/example/backend/security/jwt/filter/UserStatusCheckFilter.java, backend/src/main/java/com/example/backend/security/jwt/service/TokenService.java, backend/src/main/java/com/example/backend/security/jwt/util/JwtTokenizer.java, backend/src/main/java/com/example/backend/user/controller/UserController.java
필터에 정지된 사용자 요청 차단 로직 추가
<br>
#55 
<br>
필터에 정지된 사용자 요청 차단 로직 추가
<br>
=> [ back / feat ] 55  : 필터에 정지된 사용자 요청 차단 로직 추가

backend/src/main/java/com/example/backend/exception/ExceptionCode.java, backend/src/main/java/com/example/backend/inventoryIn/service/InventoryInService.java, backend/src/main/java/com/example/backend/inventoryOut/service/InventoryOutService.java, backend/src/main/java/com/example/backend/itemInstance/controller/ItemInstanceController.java, backend/src/main/java/com/example/backend/itemInstance/dto/request/CreateItemInstanceRequestDto.java, backend/src/main/java/com/example/backend/itemInstance/dto/request/UpdateItemInstanceStatusRequestDto.java, backend/src/main/java/com/example/backend/itemInstance/dto/response/ItemInstanceResponseDto.java, backend/src/main/java/com/example/backend/itemInstance/entity/ItemInstance.java, backend/src/main/java/com/example/backend/itemInstance/repository/ItemInstanceRepository.java, backend/src/main/java/com/example/backend/itemInstance/service/ItemInstanceService.java
=> [ back/feat ] 41 : 개별자산단위

backend/build.gradle.kts, backend/src/main/java/com/example/backend/export/controller/ExcelExportController.java, backend/src/main/java/com/example/backend/export/service/ExcelExportService.java, backend/src/main/java/com/example/backend/inventoryIn/service/InventoryInService.java, backend/src/main/java/com/example/backend/inventoryOut/service/InventoryOutService.java
엑셀기능추가: 비품,개별자산단위,입고,출구,비품요청서 가능
=> [ back/feat ] 60 : 엑셀기능추가: 비품,개별자산단위,입고,출구,비품요청서 가능

backend/src/main/java/com/example/backend/analysis/controller/InventoryAnalysisController.java, backend/src/main/java/com/example/backend/analysis/dto/CategorySummaryDTO.java, backend/src/main/java/com/example/backend/analysis/dto/ItemUsageFrequencyDTO.java, backend/src/main/java/com/example/backend/analysis/dto/MonthlyInventoryDTO.java, backend/src/main/java/com/example/backend/analysis/service/InventoryAnalysisService.java, backend/src/main/java/com/example/backend/export/service/ExcelExportService.java, backend/src/main/java/com/example/backend/inventoryIn/repository/InventoryInRepository.java, backend/src/main/java/com/example/backend/inventoryIn/service/InventoryInService.java, backend/src/main/java/com/example/backend/inventoryOut/repository/InventoryOutRepository.java, backend/src/main/java/com/example/backend/inventoryOut/service/InventoryOutService.java, backend/src/main/java/com/example/backend/item/controller/ItemController.java, backend/src/main/java/com/example/backend/item/repository/ItemRepository.java, backend/src/main/java/com/example/backend/item/service/ItemService.java, backend/src/main/java/com/example/backend/redis/CacheController.java, backend/src/main/java/com/example/backend/redis/RedisConfig.java, backend/src/main/java/com/example/backend/security/config/SecurityConfigJuseyo.java
- 비품 수량 적은순/많은순 정렬
- 카테고리 별 비품 분석
- 월별 출고량/입고량 분석 (후순위로 처리)
- 품목별 사용 빈도 분석 (출고 내역 기준)
<br>
> closed #61
<br>
- 비품 데이터 테이블에 수량 기준 정렬 기능 추가 (적은순/많은순)
- 카테고리별 비품 수량/종류 분석 로직 구현 및 
- 월별 출고/입고 데이터 집계 
- 출고 내역을 기반으로 한 품목별 사용 빈도 분석 로직 추가
<br>
=> [ back / feat ] 61 : 통계 기능

backend/build.gradle.kts, backend/src/main/java/com/example/backend/email/service/EmailService.java, backend/src/main/java/com/example/backend/managementDashboard/controller/ManagementController.java, backend/src/main/java/com/example/backend/managementDashboard/dto/ManagementDashBoardRequestDto.java, backend/src/main/java/com/example/backend/managementDashboard/service/ManagementDashboardService.java
관리 페이지 Dto 수정
<br>
#77 
<br>
관리 페이지 Dto 이름 수정 
<br>
선택)
=> [ back / feat ] 77  : 관리 페이지 Dto 수정

backend/src/main/java/com/example/backend/managementDashboard/controller/ManagementController.java
관리 페이지 단건 조회 권한 수정
<br>
> closed #80 
<br>
관리 페이지 단건 조회 권한 수정 
기존 ADMIN, MANAGER
현재 ADMIN, MANAGER, USER
<br>
=> [ back / feat ] 80 : 관리 페이지 단건 조회 권한 수정

backend/build.gradle.kts, backend/src/main/java/com/example/backend/config/AwsS3Config.java, backend/src/main/java/com/example/backend/exception/ExceptionCode.java, backend/src/main/java/com/example/backend/image/service/ImageService.java, backend/src/main/java/com/example/backend/utils/CreateRandomNumber.java, backend/src/main/java/com/example/backend/utils/ImageUtil.java, backend/src/main/java/com/example/backend/utils/S3Uploader.java
s3 이미지 기능 구현 crud
<br>
#85 
<br>
이미지 기능 구현 CRUD 
<br>
=> [ back / feat ] 85 : s3 이미지 기능 구현 crud

backend/src/main/java/com/example/backend/managementDashboard/controller/ManagementController.java
[ back / feat ] 88 : 같은 관리페이지 내 매니저 조회
<br>
#88 
=> [ back / feat ] 88 : 같은 관리페이지 내 매니저 조회

backend/src/main/java/com/example/backend/exception/ExceptionCode.java, backend/src/main/java/com/example/backend/supplyRequest/controller/SupplyRequestController.java, backend/src/main/java/com/example/backend/supplyRequest/repository/SupplyRequestRepository.java, backend/src/main/java/com/example/backend/supplyRequest/service/SupplyRequestService.java
[ back / refact ] 90 : 비품요청서수정
<br>
#90 
<br>
일반회원은 자신의 글만 조회, 수정
매니저는 모든글 조회, 본인글 수정
=> [ back / refact ] 90 : 비품요청서수정

backend/src/main/java/com/example/backend/inventoryOut/service/InventoryOutService.java, backend/src/main/java/com/example/backend/notification/controller/NotificationController.java, backend/src/main/java/com/example/backend/security/config/SecurityConfigJuseyo.java, frontend/package-lock.json, frontend/package.json, frontend/src/app/ClientLayout.tsx, frontend/src/app/page.tsx, frontend/src/components/Notification/NotificationBell.tsx, frontend/src/stores/notifications.ts
알림 인증 문제 해결
front 테스트 환경 조성
<br>
> closed #100 
<br>
eventsource가 헤더를 가질 수 없어 쿠키에서 토큰을 꺼내도 서버로 전송하지 못함 -> 인증 불가
eventsource 대신 fetch + readableStream 사용 -> credentials: "include" 사용가능 -> 쿠키로 인증!
<br>
=> [ back / refact ] 100 : 알림 인증 문제 해결, front 테스트 환경 조성

backend/src/main/java/com/example/backend/user/controller/UserController.java, backend/src/main/java/com/example/backend/user/service/UserService.java
user 충돌 해결 
<br>
#110 
<br>
user 충돌 해결 
<br>
=> [ back / fix ] 110 : 메인 에러 해결

frontend/src/app/ClientLayout.tsx, frontend/src/app/chat/page.tsx, frontend/src/app/layout.tsx
프론트 로그인 에러 해결 
<br>
#112 
<br>
프론트 로그인 에러 해결 
<br>
=> [ front / feat ] 112 : 프론트 로그인 에러 해결

backend/src/main/java/com/example/backend/chat/handler/StompHandler.java, backend/src/main/java/com/example/backend/redis/RefreshToken.java, backend/src/main/java/com/example/backend/security/jwt/filter/JwtAuthenticationFilter.java, backend/src/main/java/com/example/backend/security/jwt/service/TokenService.java, backend/src/main/java/com/example/backend/security/jwt/util/JwtTokenizer.java, backend/src/main/java/com/example/backend/user/controller/UserController.java
refreshToken을 통해 accessToken 재발급 구현 완료 
<br>
#130 
<br>
refreshToken을 통해 accessToken 재발급 구현 완료 
<br>
=> [ back / feat ] : 130 refreshtoken 으로 accesstoken 재발급

backend/src/main/java/com/example/backend/category/controller/CategoryController.java, backend/src/main/java/com/example/backend/category/repository/CategoryRepository.java, backend/src/main/java/com/example/backend/category/service/CategoryService.java, backend/src/main/java/com/example/backend/exception/GlobalExceptionHandler.java, backend/src/main/java/com/example/backend/security/config/SecurityConfigJuseyo.java
카테고리 시큐리티 컨피그 추가 후 role, management 예외처리 에러 리팩토링
<br>
> closed #133 
<br>
시큐리티 컨피그 - 카테고리 부분 추가
카테고리 - role, management 예외처리 관련 코드 리팩토링
- CategoryController
- CategoryService
<br>
=> [ Back / refact ] : 133 카테고리 시큐리티 컨피그 추가

backend/src/main/java/com/example/backend/search/controller/SearchController.java, backend/src/main/java/com/example/backend/user/repository/UserRepository.java, backend/src/main/java/com/example/backend/user/service/UserService.java
검색 - 회원 검색 - 일반 회원만 검색 결과에 나오는 검색 기능 추가
<br>
> closed #137 
<br>
검색 - 회원 검색 - 일반 회원만 조회 기능 추가
- SearchController
유저 부분 - 회원 검색 - 일반 회원만 조회 기능 관련 코드 추가
- UserRepository
- UserService
management, role, approval 예외 테스트 완료
<br>
같은 관리 페이지(1)  + 승인된(approved) + 일반 회원(2)만 조회
=> [ Back / feat ] : 137 검색 - 회원 검색 - 일반 회원만 조회 기능 추가

backend/src/main/java/com/example/backend/chat/chatMessage/entity/ChatMessage.java, backend/src/main/java/com/example/backend/chat/chatMessage/repository/ChatMessageRepository.java, backend/src/main/java/com/example/backend/chat/chatMessage/service/ChatMessageService.java, backend/src/main/java/com/example/backend/chat/chatUser/entity/ChatUser.java, backend/src/main/java/com/example/backend/chat/chatUser/repository/ChatUserRepository.java, backend/src/main/java/com/example/backend/chat/chatroom/controller/ChatRoomController.java, backend/src/main/java/com/example/backend/chat/chatroom/service/ChatRoomService.java, frontend/src/app/chat/user/page.tsx, frontend/src/components/chat/ChatRoomList.tsx
새로운 채팅이 존재한다면 new 볼 수 있게 
<br>
#139 
<br>
새로운 채팅이 존재한다면 new 볼 수 있게 
<br>
=> [ back / feat ] 139 : 새로운 채팅이 존재한다면 new 볼 수 있게 

backend/src/main/java/com/example/backend/chat/chatroom/repository/ChatRoomRepository.java, backend/src/main/java/com/example/backend/chat/chatroom/service/ChatRoomService.java, backend/src/main/java/com/example/backend/redis/RedisService.java, backend/src/main/java/com/example/backend/security/jwt/filter/JwtAuthenticationFilter.java
메시지 최신순으로 채팅방 정렬 추가 
<br>
#144 
<br>
메시지 최신순으로 채팅방 정렬 추가 
<br>
=> [ back / feat ] : 메시지 최신순으로 채팅방 정렬

backend/src/main/java/com/example/backend/security/jwt/filter/JwtAuthenticationFilter.java
refersh쿠키 설정 변경
<br>
<br>
refersh쿠키 설정 변경
<br>
=> [ back / feat ] 146 : refersh쿠키 설정 변경

backend/src/main/java/com/example/backend/chat/chatMessage/dto/response/ChatResponseDto.java, backend/src/main/java/com/example/backend/chat/chatroom/controller/ChatRoomController.java, backend/src/main/java/com/example/backend/chat/chatroom/dto/response/OpponentResponseDto.java, backend/src/main/java/com/example/backend/chat/chatroom/service/ChatRoomService.java, backend/src/main/java/com/example/backend/security/jwt/filter/JwtAuthenticationFilter.java, backend/src/main/java/com/example/backend/security/jwt/service/TokenService.java, frontend/src/app/chat/group/page.tsx, frontend/src/app/chat/support/page.tsx, frontend/src/app/chat/user/page.tsx, frontend/src/components/chat/Chat.tsx, frontend/src/components/chat/ChatRoomList.tsx, frontend/src/components/chat/UserList.tsx
유저, 고객센터, 그룹 채팅 UI 수정 
<br>
#142 
<br>
유저, 고객센터, 그룹 채팅 UI 수정 
<br>
=> [ front / style ] : 142 유저 그룹 고객 채팅 UI

frontend/src/app/settings/categories/add/page.tsx, frontend/src/app/settings/categories/edit/[id]/page.tsx, frontend/src/app/settings/categories/page.tsx
페이지관리(settings)>카테고리 관리(categories) 페이지 프론트
<br>
> closed #143 
<br>
카테고리 관련 페이지 프론트
- 카테고리 관리 페이지
- 카테고리 추가
- 카테고리 수정
<br>
=> [ Front / style ] : 143 카테고리 관리 페이지 프론트

frontend/src/components/chat/Chat.tsx, frontend/src/components/chat/ChatRoomList.tsx
스크롤 문제, new 문제 해결
<br>
#154 
<br>
스크롤 문제, new 문제 해결
<br>
=> [ front / fix ] 154 : 스크롤 문제, new 문제 해결

backend/src/main/java/com/example/backend/supplyRequest/service/SupplyRequestService.java
비품추적서 코드 수정
<br>
#158 
<br>
비품요청서에서 대여 유무에 따라 비품추적서 이슈 변경
=> [ back / refact ] 158 : 비품추적서 코드 수정

.idea/.name, .idea/compiler.xml, .idea/gradle.xml, .idea/misc.xml, .idea/modules.xml, .idea/modules/backend.main.iml, .idea/vcs.xml, .idea/workspace.xml, frontend/src/app/supplyrequest/page.tsx
[ front/style ] 153 : 비품요청서 구현
<br>
#153 
<br>
프론트 비품요청서 구현
=> [ front/style ] 153 : 비품요청서 구현

backend/src/main/java/com/example/backend/chat/chatroom/service/ChatRoomService.java, backend/src/main/java/com/example/backend/exception/GlobalExceptionHandler.java, backend/src/main/java/com/example/backend/role/RoleService.java, backend/src/main/java/com/example/backend/role/repository/RoleRepository.java, backend/src/main/java/com/example/backend/user/dto/response/UserListResponseDto.java, backend/src/main/java/com/example/backend/user/repository/UserRepository.java, backend/src/main/java/com/example/backend/user/service/UserService.java, frontend/src/app/chat/group/page.tsx, frontend/src/app/chat/user/page.tsx, frontend/src/app/page.tsx, frontend/src/components/chat/Chat.tsx, frontend/src/components/chat/ChatRoomList.tsx
전반적인 채팅 UI 개선 
<br>
#172 
<br>
- 채팅에 상대방 이름이 나올 수 있게 구현
- 매니저는 다른 매니저를 조회할 수 있게 구현 
<br>
=> [ front / refact ] 172 : 채팅 유저 조회 수정, 채팅 UI 수정 

backend/src/main/java/com/example/backend/supplyReturn/controller/SupplyReturnController.java, backend/src/main/java/com/example/backend/supplyReturn/dto/request/SupplyReturnStatusUpdateRequestDto.java, backend/src/main/java/com/example/backend/supplyReturn/service/SupplyReturnService.java
반납 요청 승인 시 비품 이미지 추가
<br>
> closed #177
=> [ back / fix ] 177 : 반납 요청 승인 시 비품 이미지 추가

frontend/package-lock.json, frontend/package.json, frontend/src/app/itemview/page.tsx
비품 조회 일반 회원 프론트
<br>
> closed #212 
<br>
비품 조회 일반 회원 프론트
- itemview
<br>
=> [ front / style ] 212 : 비품 조회 일반 회원 프론트

backend/src/main/java/com/example/backend/domain/notification/dto/NotificationResponseDTO.java, backend/src/main/java/com/example/backend/domain/notification/notificationPolicy/NotificationPolicy.java, backend/src/main/java/com/example/backend/domain/notification/service/NotificationService.java, frontend/src/app/ClientLayout.tsx, frontend/src/app/notifications/page.tsx, frontend/src/components/Notification/NotificationBell.tsx, frontend/src/stores/notifications.ts
<br>
> closed #208 
<br>
알림 필터 수정
<br>
=> [ back / refact ] 208: 알림 필터 수정

backend/build.gradle.kts, backend/src/main/java/com/example/backend/domain/inventory/inventoryIn/dto/response/InventoryInResponseDto.java, backend/src/main/java/com/example/backend/domain/inventory/inventoryIn/repository/InventoryInRepository.java, backend/src/main/java/com/example/backend/domain/inventory/inventoryIn/service/InventoryInService.java, backend/src/main/java/com/example/backend/domain/inventory/inventoryOut/controller/InventoryOutController.java, backend/src/main/java/com/example/backend/domain/inventory/inventoryOut/dto/response/InventoryOutResponseDto.java, backend/src/main/java/com/example/backend/domain/inventory/inventoryOut/service/InventoryOutService.java, frontend/package-lock.json, frontend/package.json, frontend/src/app/inbound/page.tsx, frontend/src/app/outbound/page.tsx, frontend/src/components/Navigation/Navigation.tsx
입고 출고 내역 페이지
<br>
> closed #211 
<br>
<br>
=> [front / style ] 211 : 입고 출고 내역 페이지

frontend/src/app/search/page.tsx
검색 페이지 프론트
<br>
> closed #217 
<br>
검색
- 검색 페이지
- 검색 결과 화면
<br>
=> [ front / style ] 217 : 검색 페이지 프론트

backend/src/main/java/com/example/backend/domain/analysis/service/InventoryAnalysisService.java, backend/src/main/java/com/example/backend/domain/inventory/inventoryIn/repository/InventoryInRepository.java, backend/src/main/java/com/example/backend/domain/inventory/inventoryIn/service/InventoryInService.java, backend/src/main/java/com/example/backend/domain/inventory/inventoryOut/repository/InventoryOutRepository.java, backend/src/main/java/com/example/backend/domain/itemInstance/repository/ItemInstanceRepository.java, backend/src/main/java/com/example/backend/domain/registerItem/repository/RegisterItemRepository.java, backend/src/main/java/com/example/backend/domain/registerItem/service/RegisterItemService.java, backend/src/main/java/com/example/backend/domain/supply/supplyReturn/repository/SupplyReturnRepository.java, backend/src/main/java/com/example/backend/domain/supply/supplyReturn/service/SupplyReturnService.java
관리페이지 아이디 조건 추가
<br>
> closed #218
=> [ back / refactor ] 218 : 관리페이지 아이디 조건 추가

backend/src/main/java/com/example/backend/domain/recommendation/service/RecommendationService.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/controller/SupplyRequestController.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/dto/response/LentItemDto.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/repository/SupplyRequestRepository.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/service/SupplyRequestService.java, backend/src/main/java/com/example/backend/domain/supply/supplyReturn/repository/SupplyReturnRepository.java, backend/src/main/java/com/example/backend/enums/RentStatus.java, frontend/src/app/dashboard/page.tsx
일반회원 대시보드 수정
<br>
> closed #223
<br>
- 비품 추천 api 연결
- 개인 대여 물품 리스트 api 구현 및 연결
<br>
=> [ front / refactor ] 223 : 일반회원 대시보드 수정

backend/src/main/java/com/example/backend/domain/item/controller/ItemController.java, backend/src/main/java/com/example/backend/domain/item/repository/ItemRepository.java, backend/src/main/java/com/example/backend/domain/item/service/ItemService.java, backend/src/main/java/com/example/backend/global/security/config/SecurityConfigJuseyo.java, frontend/src/app/item/supplyrequest/create/page.tsx, frontend/src/app/item/supplyrequest/list/manage/page.tsx, frontend/src/app/item/supplyrequest/list/user/page.tsx, frontend/src/app/settings/categories/add/page.tsx
비품요청서수정
<br>
#221 
<br>
권한별 비품페이지 접숙 구분, 비품요청서 목록불러오기 문제 해결
<br>
=> [ front/refact ] : 221  비품요청서수정

backend/src/main/java/com/example/backend/domain/supply/supplyRequest/service/SupplyRequestService.java
거절시 재고차감 해결
<br>
#229 
<br>
거절시 재고차감 해결
=> [ back / refact ] 229 : 거절시 재고차감 해결

frontend/src/app/find/email/page.tsx, frontend/src/app/find/password/page.tsx
이메일로 비밀번호 찾기 구현
<br>
#233 
<br>
이메일로 비밀번호 찾기 구현 완료 
<br>
</br>
</br>
=> [ front / feat ] 233 : 이메일로 비밀번호 찾기 구현

backend/src/main/java/com/example/backend/domain/user/controller/UserController.java
채팅 유저 리스트 조회 API 설명 개선
<br>
#242 
<br>
채팅 유저 리스트 조회 API 설명 개선
<br>
=> [ back / refact ] 242 : /chat/list API swagger 설명 개선

frontend/src/app/signup/manager/page.tsx, frontend/src/app/signup/managerinfo/page.tsx, frontend/src/app/signup/select/page.tsx
일반 매니저 회원가입 구현 
<br>
#238 
<br>
회원가입 전 관리페이지 입력 검증
이메일, 핸드폰번호 인증 해야 회원가입 가능 
<br>
=> [ front / feat  ] 238 : 일반 매니저 회원가입 구현

frontend/src/app/signup/initial/page.tsx
최초 매니저 회원가입 구현 완료
<br>
#246 
<br>
최초 매니저 회원가입 구현
이메일, 핸드폰 인증 안되면 가입 불가능 
<br>
=> [ front / feat ] 236 : 최초 매니저 회원가입 구현 완료

frontend/src/app/login/type/page.tsx, frontend/src/app/signup/initial/page.tsx, frontend/src/app/signup/manager/page.tsx, frontend/src/app/signup/member/page.tsx, frontend/src/app/signup/page.tsx, frontend/src/app/signup/select/page.tsx
로그인-회원가입 페이지 수정
<br>
> closed #228
<br>
<br>
=> [ front / refactor ] 228 : 로그인-회원가입 페이지 수정

frontend/src/app/ClientLayout.tsx, frontend/src/app/admin/request/page.tsx, frontend/src/stores/auth/loginMember.tsx
- 관리 페이지 생성 페이지 수정 및 관리 페이지 생성 후 부서 관리로 리 다이렉트 
<br>
> closed #252
<br>
=> [ front / refactor ] 252 : 관리페이지 생성 페이지 수정

backend/src/main/java/com/example/backend/domain/user/controller/UserController.java, backend/src/main/java/com/example/backend/domain/user/dto/response/UserProfileResponseDto.java, backend/src/main/java/com/example/backend/domain/user/service/UserService.java, backend/src/main/java/com/example/backend/global/security/config/SecurityConfigJuseyo.java, backend/src/main/java/com/example/backend/global/security/jwt/filter/UserStatusCheckFilter.java, frontend/src/app/ClientLayout.tsx, frontend/src/app/dashboard/page.tsx, frontend/src/app/settings/approve/page.tsx, frontend/src/stores/auth/loginMember.tsx
회원 승인, 거부, 삭제 구현 
<br>
#250
<br>
- 권한 및 승인 관리 요약
매니저 역할 사용자만 관리 기능 사용 가능
승인 요청(Requested) 또는 거부(Rejected) 상태 사용자는 관리 페이지 접근 불가
- 매니저 권한 구분
최초 매니저: 매니저, 회원 모두 승인/거부/삭제 가능
일반 매니저: 일반 회원만 승인/거부/삭제 가능
<br>
=> [ front / feat ] 250 : 회원 승인 거부 삭제 구현

backend/src/main/java/com/example/backend/domain/inventory/inventoryOut/controller/InventoryOutController.java, backend/src/main/java/com/example/backend/domain/inventory/inventoryOut/service/InventoryOutService.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/service/SupplyRequestService.java, backend/src/main/java/com/example/backend/global/security/config/SecurityConfigJuseyo.java, frontend/src/app/outbound/page.tsx, frontend/src/app/settings/categories/add/page.tsx
출고내역생성
<br>
#231 
<br>
출고내역 프론트 기능구현, 비품요청서 대여서 지급으로 나가는 문제 해결.
<br>
=> [ front/style ] 231 : 출고내역생성

backend/src/main/java/com/example/backend/global/exception/GlobalExceptionHandler.java, frontend/package-lock.json, frontend/package.json, frontend/src/app/layout.tsx, frontend/src/app/settings/categories/add/page.tsx, frontend/src/app/settings/categories/edit/[id]/page.tsx, frontend/src/app/settings/categories/page.tsx
<br>
<br>
카테고리 관리 프론트 구현
- 카테고리 관리 페이지
- 카테고리 추가 페이지
- 카테고리 수정 페이지
- 카테고리 삭제 기능
테스트
- 카테고리 CRUD 테스트 완료
- 관리페이지 내 중복 추가 시 예외 처리 테스트 완료
- 롤 별 예외 처리 테스트 완료
<br>
=> [ front / feat ] 253 : 카테고리 관리, 추가, 수정, 삭제 구현

backend/src/main/java/com/example/backend/domain/itemInstance/dto/response/ItemInstanceResponseDto.java, backend/src/main/java/com/example/backend/domain/itemInstance/entity/ItemInstance.java, backend/src/main/java/com/example/backend/domain/itemInstance/service/ItemInstanceService.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/service/SupplyRequestService.java, frontend/src/app/item/iteminstance/page.tsx, frontend/src/app/settings/categories/add/page.tsx, frontend/src/components/Navigation/Navigation.tsx
개별자산 프론트 구현
<br>
#260 
<br>
개별자산 프론트 구현, 엔티티 수정
<br>
=> [ front/style ] 260 : 개별자산구현

backend/src/main/java/com/example/backend/domain/user/controller/UserController.java, backend/src/main/java/com/example/backend/domain/user/dto/request/ValidPasswordRequestDto.java, backend/src/main/java/com/example/backend/domain/user/entity/User.java, backend/src/main/java/com/example/backend/domain/user/service/UserService.java, backend/src/main/java/com/example/backend/global/security/config/SecurityConfigJuseyo.java, frontend/src/app/login/page.tsx, frontend/src/app/settings/approve/page.tsx, frontend/src/app/user/page.tsx, frontend/src/app/withdraw/page.tsx, frontend/src/app/withdraw/withdraw.module.css
회원 탈퇴 소프트삭제 구현 
<br>
#258 
<br>
- 회원 탈퇴 
비밀번호로 인증해야 탈퇴 페이지 접속 가능 
회원 탈퇴 시 이메일, 핸드폰번호 다시 사용 가능 
<br>
=> [ front / feat ] 258 : 회원 탈퇴 구현

frontend/src/app/ClientLayout.tsx
ClinetLayout 오류 수정
<br>
#266 
<br>
ClinetLayout 오류 수정
<br>
=> [ front / fix ] 266 : ClinetLayout 오류 수정

backend/src/main/java/com/example/backend/global/redis/RedisConfig.java
redis 비밀번호 추가, 구현 추가 
<br>
#286
<br>
reids 비밀번호 추가, 구현된거 추가 
<br>
=> [ back / feat ] 286 : redis 접속 시 비밀번호 추가, 구현 추가 

.github/workflows/deploy.yml
Update deploy.yml
<br>
> closed #269
<br>
<br>
=> [ back / deploy ] Update deploy.yml

backend/src/main/java/com/example/backend/domain/supply/supplyRequest/service/SupplyRequestService.java, frontend/src/app/item/supplyrequest/create/[id]/page.tsx, frontend/src/app/item/supplyrequest/create/page.tsx, frontend/src/app/item/supplyrequest/list/manage/page.tsx, frontend/src/app/item/supplyrequest/list/user/page.tsx
비품요청서 수정
<br>
#280 
<br>
비품요청서 승인 대기 상태일때만 수정, 삭제 가능 버튼 추가, 비품 지급 시 2중으로 지급되는 오류 수정
<br>
=> [ front/style ] 280 : 비품요청서수정

backend/src/main/resources/application-prod.yml
Update application-prod.yml
<br>
> closed #269
<br>
<br>
=> [ back / deploy ] Update application-prod.yml

frontend/.env.production, frontend/next.config.js
프론트 배포 설정
<br>
> closed #297
<br>
<br>
=> [ front / deploy ] 297 : 프론트 배포 설정

backend/src/main/java/com/example/backend/domain/chaseItem/controller/ChaseItemController.java, backend/src/main/java/com/example/backend/domain/chaseItem/service/ChaseItemService.java, backend/src/main/java/com/example/backend/global/security/config/SecurityConfigJuseyo.java, frontend/src/app/item/chase/page.tsx, frontend/src/app/item/supplyrequest/create/page.tsx
비품추적서구현
<br>
#284 
<br>
비품추적서 구현
<br>
=> [ front/style ] 284 : 비품추적서구현

frontend/next.config.js
next.config.js에 상태체크 해제 추가
<br>
#307 
<br>
next.config.js에 상태체크 해제 추가
<br>
=> [ front / deploy ] 307 : next.config.js에 상태체크 해제 추가

backend/src/main/java/com/example/backend/domain/category/dto/response/CategoryResponseDTO.java, backend/src/main/java/com/example/backend/domain/item/controller/ItemController.java, backend/src/main/java/com/example/backend/domain/item/dto/response/ItemCardResponseDto.java, backend/src/main/java/com/example/backend/domain/item/repository/ItemRepository.java, backend/src/main/java/com/example/backend/domain/item/service/ItemService.java, backend/src/main/java/com/example/backend/domain/search/service/SearchService.java, backend/src/main/java/com/example/backend/global/redis/RedisConfig.java, backend/src/main/resources/application-prod.yml, frontend/.env.production, frontend/next.config.js, frontend/src/app/chat/select/page.tsx, frontend/src/components/Navigation/Navigation.tsx
main에 있는 코드 dev에 pull
<br>
#312 
<br>
main에 있는 코드 dev에 pull
<br>
=> [ front / feat ] 312 :  main에 있는 코드 dev에 pull

frontend/.env.production
env url 변경
<br>
> closed #297
<br>
<br>
=> [ front / deploy ] 297 : env url 변경

backend/src/main/java/com/example/backend/domain/user/controller/UserController.java, backend/src/main/java/com/example/backend/global/exception/GlobalExceptionHandler.java, backend/src/main/java/com/example/backend/global/redis/RedisConfig.java, backend/src/main/java/com/example/backend/global/security/config/SecurityConfigJuseyo.java, frontend/.env.production
배포 프론트 cors 추가, env 추가
<br>
#324 
<br>
배포 프론트 cors 추가, env 추가
<br>
=> [ back / feat ] 324 : 배포 프론트 cors 추가, env 추가

backend/src/main/java/com/example/backend/domain/chat/config/WebSocketConfig.java
웹소켓 배포 프론트 권한 추가
<br>
#326 
<br>
웹소켓 배포 프론트 권한 추가
<br>
=> [ back / feat ]326 : 웹소켓 배포 프론트 권한 추가

frontend/src/app/signup/initial/page.tsx, frontend/src/app/signup/manager/page.tsx, frontend/src/app/signup/member/page.tsx
회원가입 비밀번호 입력 형식 검증 알람
<br>
#328 
<br>
회원 가입 필드 형식이 옳바르지 않으면 알림
이름: 20자 이하
이메일: 이메일 형식 (example@domain.com)
비밀번호: 숫자, 영어, 특수문자 포함 8~20자
휴대폰 번호: 010-xxxx-xxxx 형식 
<br>
=> [ front / refact ] 328 : 회원가입 비밀번호 입력 형식 검증 알람

backend/src/main/resources/application.yml
yml 파일에 timezone 추가 
<br>
#332 
<br>
yml파일에 아래 코드 추가 
spring:
jackson:
time-zone: Asia/Seoul
<br>
=> [ back / feat ] 332 : time zone 추가

frontend/src/app/admin/request/page.tsx
최초 매니저 관리 페이지 생성 안됨 이슈 고침 
<br>
> closed #330
<br>
role 대문자로 비교
<br>
=> [ fix ] 330 : 최초 매니저 관리 페이지 생성 안됨 이슈 고침 

backend/src/main/java/com/example/backend/domain/chat/chatMessage/dto/response/ChatResponseDto.java
메시지 응답 형식 ZonedDateTime으로 변경
<br>
#335 
<br>
메시지 응답 형식 ZonedDateTime으로 변경
<br>
=> [ back / feat ] 335 : 채팅 메시지 응답 형식 ZonedDatTime으로 변경

backend/src/main/resources/application.yml
flask-recommender url 변경
배포 서버 내 도커 컨테이너 이름으로 변경
<br>
> closed #342
<br>
<br>
=> [ back / refact ] 342 : flask-recommender url 변경

frontend/src/app/chat/group/page.tsx, frontend/src/app/chat/user/page.tsx, frontend/src/components/chat/Chat.tsx, frontend/src/components/chat/ChatRoomList.tsx, frontend/src/components/chat/UserList.tsx
전반적인 채팅 디자인 수정 
<br>
#323 
<br>
- 채팅방 메시지, 입력창 등 전체적인 색상 및 스타일 개선
- 채팅 입력창을 둥글고 세련되게 변경, 전송 버튼 스타일 강조
- 채팅 메시지 날짜, 말풍선, NEW 뱃지 등 UI 스타일 업그레이드
- 채팅방 헤더, 유저 리스트, 채팅방 리스트 등 버튼 및 텍스트 스타일 통일
- 입력 글자수 제한(200자) 및 카운트 표시 추가
- 이름/부서 등 긴 텍스트 툴팁(hover)로 전체 보기 적용
- 모달, 리스트 등 레이아웃 및 배경 스타일 개선
<br>
=> [ front / style ] 323 : 채팅 스타일 변경

frontend/src/components/chat/Chat.tsx, frontend/src/components/chat/ChatRoomList.tsx, frontend/src/utils/leaveChatRoom.ts
채팅방 나가기 오류 수정
<br>
> closed #364
<br>
채팅방 나가기 오류 수정
<br>
=> [ front / fix ] 364 : 채팅방 나가기 오류 수정

backend/src/main/java/com/example/backend/global/security/config/SecurityConfigJuseyo.java
배포 서버 cors추가
<br>
#365 
<br>
배포 서버 cors추가
<br>
=> [ back / refact ]  365 : 배포 서버 cors추가

backend/src/main/java/com/example/backend/domain/user/sms/service/SmsService.java, backend/src/main/java/com/example/backend/global/utils/CreateRandomNumber.java
핸드폰 인증번호 숫자 6자리로 변경
<br>
#368 
<br>
핸드폰 인증번호 숫자 6자리로 변경
<br>
=> [ back / refact ] 368 : 핸드폰 인증번호 숫자 6자리로 변경

backend/src/main/java/com/example/backend/domain/notification/service/NotificationService.java, frontend/src/app/ClientLayout.tsx, frontend/src/components/Notification/NotificationBell.tsx
알림에 eventsource 사용
<br>
> closed #352 
<br>
<br>
=> [ front / refact ] 352: eventsource 사용

backend/src/main/java/com/example/backend/domain/notification/entity/NotificationType.java, backend/src/main/java/com/example/backend/domain/notification/event/NewUserApprovedEvent.java, backend/src/main/java/com/example/backend/domain/notification/event/NewUserEvent.java, backend/src/main/java/com/example/backend/domain/notification/event/NewUserRejectedEvent.java, backend/src/main/java/com/example/backend/domain/notification/event/NotificationEventListener.java, backend/src/main/java/com/example/backend/domain/notification/notificationPolicy/NotificationPolicy.java, backend/src/main/java/com/example/backend/domain/notification/service/alert/NewUserApprovedNotificationService.java, backend/src/main/java/com/example/backend/domain/notification/service/alert/NewUserNotificationService.java, backend/src/main/java/com/example/backend/domain/notification/service/alert/NewUserRejectedNotificationService.java, backend/src/main/java/com/example/backend/domain/notification/service/scheduler/NotReturnedYetMonitoringService.java, backend/src/main/java/com/example/backend/domain/notification/strategy/context/NewUserContext.java, backend/src/main/java/com/example/backend/domain/notification/strategy/factory/NotificationStrategyFactory.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/NewDashboardApprovedStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/NewDashboardRejectedStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/NewManagerApprovedStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/NewManagerRejectedStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/NewManagerStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/NewUserApprovedStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/NewUserRejectedStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/NewUserStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/SupplyRequestApprovedStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/SupplyRequestDelayedStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/SupplyRequestRejectedStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/SupplyReturnApprovedStrategy.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/SupplyReturnStrategy.java, backend/src/main/java/com/example/backend/domain/user/service/UserService.java, frontend/src/app/notifications/page.tsx, frontend/src/components/Notification/NotificationBell.tsx, frontend/src/stores/notifications.ts
브라우저 간 알림 전파
<br>
<br>
sse 연결: fetch -> eventsource
회원가입, 회원가입 승인, 회원가입 거부 알림 추가
알림 전략 컨텍스트 검사 수정
알림벨 읽음처리 전파
알림벨 알림 생성 시 전파
<br>
=> [ front / refact ] 352 : 브라우저 간 알림 전파

backend/src/main/java/com/example/backend/domain/notification/entity/NotificationType.java, backend/src/main/java/com/example/backend/domain/notification/service/NotificationService.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/SupplyRequestStrategy.java, frontend/src/app/ClientLayout.tsx, frontend/src/app/notifications/page.tsx, frontend/src/components/Notification/NotificationBell.tsx, frontend/src/stores/notifications.ts
sse 기본 타임아웃 1시간 -> 5분으로 변경
<br>
> closed #381 
<br>
<br>
=> [ back / refact ] sse 기본 타임아웃 1시간 -> 5분으로 변경

frontend/src/app/notifications/page.tsx
front 오류 해결 후 main으로 push 
<br>
<br>
front 오류 해결 후 main으로 push 
<br>
=> [ front / fix ] : front 오류 해결 후 main으로 push 

backend/src/main/java/com/example/backend/domain/chat/chatroom/dto/response/OpponentResponseDto.java, backend/src/main/java/com/example/backend/domain/chat/chatroom/repository/ChatRoomRepository.java, backend/src/main/java/com/example/backend/domain/chat/chatroom/service/ChatRoomService.java, frontend/src/components/chat/ChatRoomList.tsx, frontend/src/components/chat/UserList.tsx
유저 리스트 가나다 순 정렬, 채팅 메시지 최신순 채팅방 정렬 
<br>
#394 
<br>
- 유저 리스트 가나다 순 정렬
-  ( 새로운 채팅방 생성된 것이 먼저 오도록 구현) 채팅 메시지 최신순 기준 채팅방 정렬
<br>
=> [ front / refact  ] 394 : 유저 리스트 가나다 순 정렬, 채팅 메시지 최신순 채팅방 정렬 

frontend/src/app/item/iteminstance/manage/page.tsx, frontend/src/app/item/manage/page.tsx, frontend/src/components/Navigation/Navigation.tsx
네비게이션 수정
<br>
> closed #402
<br>
네비게이션 수정
<br>
=> [ front / refact ] 402 : 네비게이션 수정

frontend/src/app/inbound/page.tsx, frontend/src/app/item/chase/page.tsx, frontend/src/app/item/supplyrequest/list/manage/page.tsx, frontend/src/app/item/supplyrequest/list/user/page.tsx, frontend/src/app/item/user/page.tsx, frontend/src/app/outbound/page.tsx, frontend/src/app/settings/approve/page.tsx, frontend/src/app/settings/approve/search/page.tsx, frontend/src/components/Navigation/Navigation.tsx
페이지들 디자인수정
<br>
> closed #409
<br>
- 사용자 관리/검색 페이지 수
- 비품 추적 로그 페이지 레이아웃 수정
- 비품 요청 내역 페이지 레이아웃 수정
- 나의 비품 요청 내역 레이아웃 수정
- 비품 조회 페이지 레이아웃 수정
- 입고, 출고 내역 레이아웃 수정
<br>
=> [ front / refact ] 409 : 페이지들 디자인수정

backend/src/main/java/com/example/backend/domain/itemInstance/dto/response/ItemInstanceResponseDto.java, backend/src/main/java/com/example/backend/domain/itemInstance/entity/ItemInstance.java, backend/src/main/java/com/example/backend/domain/itemInstance/service/ItemInstanceService.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/controller/SupplyRequestController.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/service/SupplyRequestService.java, frontend/src/app/item/iteminstance/manage/page.tsx, frontend/src/app/item/iteminstance/page.tsx, frontend/src/app/item/supplyrequest/edit/[id]/page.tsx
개별자산관리수정
<br>
#393 
<br>
개별자산관리 반납일 추가
<br>
=> [ front / refact ] 393 : 개별자산관리수정

frontend/src/components/Navigation/Navigation.tsx
네비게이션 디자인 수정
<br>
#417 
<br>
매니저, 회원 네비게이션 이동 수정 
<br>
=> [ front / refact ] 417 : 네비게이션 디자인 수정

frontend/src/app/item/detail/[id]/page.tsx, frontend/src/app/item/manage/page.tsx, frontend/src/app/item/user/page.tsx
비품조회수정
<br>
#412 
<br>
비품대여 조회 중복 표시로 인하여 하나 삭제
비품관리 검색,카테고리 가시성 향상
관리열 수정
이미지 클릭시 상세페이지로 이동
<br>
=> [ front / refect ] 412 : 비품조회수정

backend/src/main/java/com/example/backend/domain/managementDashboard/service/ManagementDashboardService.java, backend/src/main/java/com/example/backend/domain/notification/entity/NotificationType.java, backend/src/main/java/com/example/backend/domain/notification/event/NewDashboardEvent.java, backend/src/main/java/com/example/backend/domain/notification/event/NotificationEventListener.java, backend/src/main/java/com/example/backend/domain/notification/notificationPolicy/NotificationPolicy.java, backend/src/main/java/com/example/backend/domain/notification/service/alert/NewDashboardNotificationService.java, backend/src/main/java/com/example/backend/domain/notification/strategy/context/NewDashboardContext.java, backend/src/main/java/com/example/backend/domain/notification/strategy/factory/NotificationStrategyFactory.java, backend/src/main/java/com/example/backend/domain/notification/strategy/strategy/NewDashboardStrategy.java, frontend/src/app/notifications/page.tsx, frontend/src/components/Notification/NotificationBell.tsx
매니저 권한 요청 알림 클릭 시 관련 페이지 이동,
채팅 알림 클릭 시 관련 페이지 이동,
새로운 관리 페이지 알림 주석(어드민)
<br>
> closed #404 
<br>
매니저 권한 요청 알림 클릭 시 관련 페이지 이동,
채팅 알림 클릭 시 관련 페이지 이동,
새로운 관리 페이지 알림 주석(어드민)
<br>
=> [ front / refact ] 404: 알림 클릭 시 관련 페이지 이동

backend/src/main/java/com/example/backend/domain/notification/controller/TestNotificationController.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/repository/SupplyRequestRepository.java, backend/src/main/java/com/example/backend/domain/supply/supplyReturn/controller/SupplyReturnController.java, backend/src/main/java/com/example/backend/domain/supply/supplyReturn/dto/request/SupplyReturnRequestDto.java, backend/src/main/java/com/example/backend/domain/supply/supplyReturn/entity/SupplyReturn.java, backend/src/main/java/com/example/backend/domain/supply/supplyReturn/repository/SupplyReturnRepository.java, backend/src/main/java/com/example/backend/domain/supply/supplyReturn/service/SupplyReturnService.java, frontend/src/app/inbound/page.tsx, frontend/src/app/item/return/manage/page.tsx, frontend/src/app/item/return/page.tsx, frontend/src/app/item/supplyeturn/create/page.tsx, frontend/src/app/item/supplyeturn/page.tsx, frontend/src/app/item/supplyrequest/list/manage/page.tsx, frontend/src/app/item/supplyrequest/list/user/page.tsx, frontend/src/app/item/supplyrequest/manage/page.tsx, frontend/src/app/outbound/page.tsx, frontend/src/app/settings/approve/search/page.tsx, frontend/src/components/Navigation/Navigation.tsx
비품 반납, 반납 요청 내역 페이지 생성
<br>
> closed #418
<br>
비품 반납, 반납 요청 내역 페이지 생성
<br>
=> [ front / style ] 418 :  비품 반납, 반납 요청 내역 페이지 생성

frontend/src/app/search/page.tsx
검색 결과 비품 조회 액션 추가
<br>
> closed #386 
<br>
- 검색 결과 화면
- 조회 액션 추가
- 검색 페이지 상태 관리 테스트 완료
<br>
=> [ front / refact ] 386 : 검색 결과 비품 조회 액션 추가

backend/src/main/java/com/example/backend/domain/user/controller/UserController.java
회원 탈퇴시 토큰도 같이 삭제
<br>
#447 
<br>
회원 탈퇴 시 토큰도 같이 삭제 
<br>
=> [ front / feat ] 447 : 회원 탈퇴시 토큰도 같이 삭제

frontend/src/app/item/supplyrequest/manage/page.tsx, frontend/src/components/Navigation/Navigation.tsx
네비게이션 바 , 날짜 수정
<br>
#451 
<br>
네비게이션 바 , 날짜 수정
<br>
=> [ front / refact ] 451 : 네비게이션 바 , 날짜 수정

backend/src/main/java/com/example/backend/domain/supply/supplyRequest/controller/SupplyRequestController.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/repository/SupplyRequestRepository.java, backend/src/main/java/com/example/backend/domain/supply/supplyRequest/service/SupplyRequestService.java, backend/src/main/java/com/example/backend/domain/supply/supplyReturn/controller/SupplyReturnController.java, frontend/src/app/item/supplyeturn/create/page.tsx
비품 반납서 수정 
<br>
#461 
<br>
비품 반납서 생성 시, 이미 생성된 비품 요청서는 조회 불가 
비품 반납서 생성 시 , 비품 대여용이 아닌 지급용 요청서는 조회 불가
<br>
=> [ back / refact ] 461 : 비품 반납서 수정

frontend/src/components/chat/ChatRoomList.tsx
고객센터 채팅 new 버튼 수정 
<br>
#463 
<br>
고객센터 채팅 new 버튼 수정 
<br>
=> [ front / refact ] 463 : 고객센터 채팅 new 버튼 뜨게

backend/src/main/java/com/example/backend/domain/item/service/ItemService.java, frontend/src/components/chat/ChatRoomList.tsx
instance 코드 주석 
<br>
<br>
instance 코드 주석 
<br>
=> [ back / refact ] : dev 코드 main에 push , instance 코드 주석 

frontend/src/app/item/detail/[id]/page.tsx, frontend/src/app/item/supplyeturn/page.tsx
회원은 출고 내역 안보이게
<br>
#481
<br>
회원은 출고 내역 안보이게
<br>
=> [ front / refact ] 481 : 회원은 출고 내역 안보이게

frontend/src/app/ClientLayout.tsx, frontend/src/app/signup/select/page.tsx
리다이렉트 수정
<br>
#485 
<br>
리다이렉트 수정
<br>
=> [ front / refact ] 485 : 리다이렉트 수정

frontend/src/app/chat/support/page.tsx
고객센터 채팅에서 매니저일 경우 채팅방 생성 안되게
<br>
#493 
<br>
고객센터 채팅에서 매니저일 경우 채팅방 생성 안되게
<br>
=> [ front / refact ] 493 : 고객센터 채팅에서 매니저일 경우 채팅방 생성 안되게

backend/src/main/java/com/example/backend/domain/item/repository/ItemRepository.java, backend/src/main/java/com/example/backend/domain/item/service/ItemService.java
비품 추가 시 관리 페이지 내에서 비품 중복 검사
<br>
#501 
<br>
비품 추가 시 관리 페이지 내에서 비품 중복 검사
<br>
=> [ back / refact ] 501 : 비품 추가 시 관리 페이지 내에서 비품 중복 검사
